// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InstallKoSync(arg1:string,arg2:string):Promise<boolean>;

export function ListKoboDevices():Promise<Array<main.KoboDevice>>;
